version: "3.8"

services:
# ##> BASE DE DONNÉES // ADMINER ET mariadb
  adminer:
    platform: linux/x86_64
    container_name: adminer_auth_4.8.1
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 80:8888
    env_file:
      - .env
      - config/.env.local
    depends_on:
      - database

###> doctrine/doctrine-bundle ###
  database:
    platform: linux/x86_64
    container_name: mariadb_auth_11.3.2
    image: mariadb:11.3.2
    restart: unless-stopped
    env_file:
      - .env
      - config/.env.local
    # volumes:
    #   - ../${FOLDER_DATASQL}:/docker-entrypoint-initdb.d/
    #   - ../${FOLDER_DATABASE}:/var/lib/mysql
    ports:
      - 3306:3306
###< doctrine/doctrine-bundle ###
# ##< BASE DE DONNÉES // ADMINER ET mariadb


volumes:
###> doctrine/doctrine-bundle ###
  auth_mariabd:
###< doctrine/doctrine-bundle ###
