# Exemple d'utilisation du workflow de vÃ©rification PR vers HOMOL avec version
# Ce workflow s'assure que seules les PR de develop vers homol sont autorisÃ©es

name: ðŸ”’ VÃ©rification PR develop â†’ homol

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - homol

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check_pr_source_homol:
    name: ðŸ”’ VÃ©rification PR develop â†’ homol
    uses: LeZouzouEnWeb/workflows/.github/workflows/homol-check-pr-depuis-dev.yml@V1.0.4
    permissions:
      contents: read
      issues: write
      pull-requests: write
